FROM nginx:latest

WORKDIR /app
RUN apt-get update && \
    apt-get install nano -y

COPY ./index.html /usr/share/nginx/html/
COPY assets /usr/share/nginx/html/assets/

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]